# Generated by Django 5.1.3 on 2024-11-13 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tEvents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tevent',
            name='type',
            field=models.CharField(blank=True, choices=[('concert', 'Concert'), ('convention', 'Convention'), ('sport', 'Sport'), ('digital', 'Digital')], max_length=10),
        ),
    ]
