# Generated by Django 5.1.3 on 2024-11-20 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tEvents', '0002_alter_tevent_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='tEvent',
        ),
        migrations.AddField(
            model_name='comments',
            name='eventId',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='tevent',
            name='coverImg',
            field=models.CharField(max_length=1000, verbose_name='Cover Image'),
        ),
        migrations.AlterField(
            model_name='tevent',
            name='isCanceled',
            field=models.BooleanField(default=False, verbose_name='Is Canceled'),
        ),
        migrations.AlterField(
            model_name='tevent',
            name='startDate',
            field=models.DateTimeField(verbose_name='Start Date'),
        ),
    ]
