# Generated by Django 5.1.3 on 2024-11-21 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tEvents', '0006_alter_comments_body_alter_comments_creator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tevent',
            options={'ordering': ['id']},
        ),
    ]
